### ISSUE TITLE
bluebird

### ISSUE THREAD

**Issue by syzer** [rafaelkaufmann/q-orm#1]
Why not to use bluebird to automatically wrap all orm API and convert to promises?
https://github.com/petkaantonov/bluebird

**Comment by rafaelkaufmann** [comment]
Good question, @syzer. If you check the `bluebird` branch on the repository (which is what I'm currently using in production for my app), it also does not use bluebird's "wrap all" feature. In essence, we need not only to promisify methods, but also make them return instances whose methods are also promisified, and so on and so forth.

**Comment by rafaelkaufmann** [comment]
Also, the orm API isn't uniform in the sense that not all of the methods follow nodeback convention, etc. So I've just converted the methods that do work...

**Comment by syzer** [comment]
non uniform API is a big problem.
I have other issue with ORM (not the q version especially)
ORM is that is very slow. It uses whole CPU thread to recover 17mb data and json it over the wire.
Also takes approx 700mb RAM.
Also because the CPU bound all other queries/requests are blocked from execution :(. 
So I found myself using it less and less, on production (moved towards simple query)

**Comment by rafaelkaufmann** [comment]
I agree, it's not a very good design. One thing that particularly bugs me
is that the main objects (models and instances) are not instances of a
common prototype, but instantiated as fresh objects everytime, which (a) is
bad JavaScript practice, (b) makes it difficult to build custom behavior
(such as eventing), (c) is a performance killer.

2014-11-25 16:41 GMT-02:00 syzer notifications@github.com:

> non uniform API is a big problem.
> I have other issue with ORM (not the q version especially)
> ORM is that is very slow. It uses whole CPU thread to recover 17mb data
> and json it over the wire.
> Also takes approx 700mb RAM.
> Also because the CPU bound all other queries/requests are blocked from
> execution :(.
> So I found myself using it less and less, on production (moved towards
> simple query)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rafaelkaufmann/q-orm/issues/1#issuecomment-64449143.

## 

_Rafael Kaufmann_
CTO

Av Atlântica 734 401
22020-010 . Rio de Janeiro . RJ

_c_ 55 21 98220.7030

rafael.kaufmann@resolveai.com.br
www.resolveai.com.br

Esta mensagem e seus anexos podem conter informações privilegiadas e/ou de
caráter confidencial, não podendo ser retransmitidos sem autorização do
remetente.
Se você recebeu essa mensagem por engano, por favor, responda este e-mail,
excluindo-o em seguida.

This e-mail and attachments may contain confidential data or information
and may
be legally privileged, therefore cannot be read, copied, printed or
forwarded or disclosed
to any person without the sender's previous authorization. If you have
received it in error,
please reply to this e-mail notifying the sender and delete it immediately
afterwards.

**Comment by syzer** [comment]
have you tried http://sequelizejs.com/ ?

ad.b) if API would be proper(and uniform) we could DI custom behavior.

**Comment by rafaelkaufmann** [comment]
Looks good. When I started using node-orm, Sequelize was very much far
behind. Also, node-orm is/was the only ORM that supported non-relational
dbs (namely MongoDB).

2014-11-25 16:53 GMT-02:00 syzer notifications@github.com:

> have you tried http://sequelizejs.com/ ?
> 
> ad.b) if API would be proper(and uniform) we could DI custom behavior.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rafaelkaufmann/q-orm/issues/1#issuecomment-64451043.

## 

_Rafael Kaufmann_
CTO

Av Atlântica 734 401
22020-010 . Rio de Janeiro . RJ

_c_ 55 21 98220.7030

rafael.kaufmann@resolveai.com.br
www.resolveai.com.br

Esta mensagem e seus anexos podem conter informações privilegiadas e/ou de
caráter confidencial, não podendo ser retransmitidos sem autorização do
remetente.
Se você recebeu essa mensagem por engano, por favor, responda este e-mail,
excluindo-o em seguida.

This e-mail and attachments may contain confidential data or information
and may
be legally privileged, therefore cannot be read, copied, printed or
forwarded or disclosed
to any person without the sender's previous authorization. If you have
received it in error,
please reply to this e-mail notifying the sender and delete it immediately
afterwards.

**Comment by syzer** [comment]
For MongoDb : I like mongoose. Light on resources. Since 2011. It is a solid TM.
Have you tried it?

**Comment by rafaelkaufmann** [comment]
Not really... Basically, I started using node-orm for this one specific
project, and I didn't want to have to deal with separate ORMs for MongoDB
and MySQL.

2014-11-25 17:20 GMT-02:00 syzer notifications@github.com:

> For MongoDb : I like mongoose. Light on resources. Since 2011. It is a
> solid TM.
> Have you tried it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rafaelkaufmann/q-orm/issues/1#issuecomment-64455218.

## 

_Rafael Kaufmann_
CTO

Av Atlântica 734 401
22020-010 . Rio de Janeiro . RJ

_c_ 55 21 98220.7030

rafael.kaufmann@resolveai.com.br
www.resolveai.com.br

Esta mensagem e seus anexos podem conter informações privilegiadas e/ou de
caráter confidencial, não podendo ser retransmitidos sem autorização do
remetente.
Se você recebeu essa mensagem por engano, por favor, responda este e-mail,
excluindo-o em seguida.

This e-mail and attachments may contain confidential data or information
and may
be legally privileged, therefore cannot be read, copied, printed or
forwarded or disclosed
to any person without the sender's previous authorization. If you have
received it in error,
please reply to this e-mail notifying the sender and delete it immediately
afterwards.

**Comment by syzer** [comment]
I ended using orm2, and mongoose, on same project. 
I had to use native driver in some places instead of orm2 (was to slow for bulk imports). Mongoose could handle slightly more data.
Had to solve some problems with connection pools...
Still i think that ORM2 is better than Hibernate and Doctrine2
